<?php

/**
 * Implementation of hook_nodeapi.
 */
function cc_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  // Display CC participants and current-user status at top of node display.
  switch ($op) {
    case 'view':
    break;
    case 'insert':
    case 'update':
      $allowed_nodetypes = variable_get('addanother_nodetypes', array());
      if (isset($allowed_nodetypes[$node->type]) && $allowed_nodetypes[$node->type]) { // TBD: Simplify this expression.
        if (variable_get('cc_creator', TRUE)) {
          cc_add($node->nid, $node->uid);
        }
      }
    case 'load':
      // Loading in the node, is this a node we care about?.
      $allowed_nodetypes = variable_get('addanother_nodetypes', array());
      if (isset($allowed_nodetypes[$node->type]) && $allowed_nodetypes[$node->type]) { // TBD: Simplify this expression.
        // Let's add our custom values.
        if (empty($node->cc_users)) $node->cc_users = array();

        // Load CC'd users.
        $result = db_query('SELECT uid, mail, status FROM {cc_node} WHERE nid = %d', array($node->nid));
        while($cc_user = db_fetch_object($result)) {
          $uid = (empty($cc_user->uid)) ? $cc_user->mail : $cc_user->uid;
          $node->cc_users[$uid] = $cc_user;
        }
      }
    break;
  }
}

/**
 * Add a user to the carbon copy list of a node.
 *
 * @param $nid
 *   ID of node user will be added to.
 * @param $uid
 *   User to add, may be a number, object or an email address.
 */
function cc_add($nid, $uid, $status = 1) {
  // Verify $nid is a node type we care about.
  $allowed_nodetypes = variable_get('addanother_nodetypes', array());
  $node = node_load($nid);
  if ((isset($allowed_nodetypes[$node->type]) && $allowed_nodetypes[$node->type])) {
    if (!empty($node->cc_users[$uid])) {
      return FALSE; // Already exists.
    }

    $userid = 0;
    if (is_object($uid) && !empty($uid->uid) && !empty($uid->mail)) {
      $userid = $uid->uid;
      $email  = $uid->mail;
    }
    else if (is_numeric($uid) && $user = user_load($uid)) {
      $userid = $uid;
      $email  = $user->mail;
    }
    else if (valid_email_address($uid)) {
      $email = $uid;
      if ($user = user_load(array('mail' => $uid))) {
        $userid = $user->uid;
      }
    }
    else {
      return FALSE;
    }

    // With better information, let's make sure this isn't a duplicate again.
    if (($userid > 0 && !empty($node->cc_users[$userid])) || !empty($node->cc_users[$email]) ) {
      return FALSE; // Already exists.
    }

    $status = (bool) $status;
    $query = "INSERT INTO {cc_node} (nid, uid, mail, status) VALUES (%d, %d, %s, %d)";
    if ($result = db_query($query, array($nid, $userid, $email, $status))) {
      return TRUE;
    } else {
      watchdog('cc', 'MySQL returned error no @errono when added user "@user" to node "@node".',
               array('@errorno' => db_error(), '@user' => $uid, '@node' => $nid));
    }
  }
  return FALSE;
}

/**
 * Admin configuration form.
 */
function cc_admin() {
  $form = array();
  $form['cc_nodes'] = array(
    '#type' => 'fieldset',
    '#title' => t('Content type settings'),
  );
  $form['cc_nodes']['cc_nodetypes'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Enable carbon copy for these content types'),
    '#options' => node_get_types('names'),
    '#default_value' => variable_get('cc_nodetypes', array()),
    '#description' => 'Carbon copy will become available for these content types. Use the options below to control what functionality will be available.',
  );

  $form['cc_display'] = array(
    '#type' => 'fieldset',
    '#title' => t('Display options'),
  );
  $form['cc_display']['cc_nodeheader'] = array(
    '#type' => 'checkbox',
    '#title' => t('Display the carbon copy forms in the node header.'),
    '#default_value' => variable_get('cc_nodeheader', TRUE),
  );
  $form['cc_display']['cc_nodefooter'] = array(
    '#type' => 'checkbox',
    '#title' => t('Display the carbon copy forms in the node footer.'),
    '#default_value' => variable_get('cc_nodefooter', TRUE),
  );
  $form['cc_display']['cc_tab'] = array(
    '#type' => 'checkbox',
    '#title' => t('Display a "CC" tab with additional options for controlling mail in queue and carbon copied users.'),
    '#default_value' => variable_get('cc_tab', FALSE),
  );
  $form['cc_display']['cc_edit'] = array(
    '#type' => 'checkbox',
    '#title' => t('Display a carbon copy text area on node creation and edit forms to allow additional users or addresses to be manually entered.'),
    '#default_value' => variable_get('cc_edit', FALSE),
  );

  $form['cc_preferences'] = array(
    '#type' => 'fieldset',
    '#title' => t('Preferences'),
  );
  $form['cc_preferences']['cc_creator'] = array(
    '#type' => 'checkbox',
    '#title' => t('Automatically add the node creator to the carbon copy list.'),
    '#default_value' => variable_get('cc_nodecreator', TRUE),
  );

  return system_settings_form($form);
}